### ISSUE TITLE
More team stats

### ISSUE THREAD

**Issue by laudiacay** [tjcsl/ctf-platform#10]
In the team info tab, under /team. We can put cutesy stuff here- most active hour of the day, problems solved, most popular problem type, first solves, rank, percentile? Just ideas, whatever works works and whatever doesn't doesn't.

**Comment by an-empty-string** [comment]
at least these:
- [ ] points histogram
- [ ] rank

**Comment by laudiacay** [comment]
most popular problem type would be pretty easy to implement too, right? We already got that list of problems that they solved in the score calculations below. We could do a percent of points pie chart by problem type, and a line graph over time of points. Percentile from rank would be easy.

**Comment by pefoley2** [comment]
Please have better graphs then mitrectf :p

**Comment by an-empty-string** [comment]
@pefoley2 we're using vis.js graph2d, it's interactive and so far is looking way nicer. if you'd like a demo pm me on irc at some point

**Comment by pefoley2** [comment]
Just about anything that actually makes sense would be better then mitrectf, I don't need a demo.

**Comment by an-empty-string** [comment]
rank stored in redis, points histogram data maybe cached?
