### ISSUE TITLE
Change around colors in the front-end

### ISSUE THREAD

**Issue by laudiacay** [tjcsl/ctf-platform#3]
Right now it looks like we nicked it from google. which we did. But let's make it TJCTF colors from last year, those are pretty, and it won't look quite so googley.

**Comment by laudiacay** [comment]
just grabbing hex color numbers that I found on the old CTF problem site here we go

glowing blue for titles: #78F8FF
slightly darker glowy blue for backgrounds: 45E6FF
darker teal for glowing blue text's shadows: 64C4C4
- [x] dark blue for background and text things: 0B6382
  This is not quite black but actually blue thing (not sure what for, maybe text? gradients?): 020C10
- [ ] A medium dark teal, our trademark blue for backgrounds and text that we are drawing attention to and buttons: 1A7A9D
  "submitted" color for the above: 3E92B2
  hover color for buttons?: 4c9fbf
  another freaking teal that they put on "active buttons" wtf: 3486A5
- [ ] UI HEADER COLOR IMPORTANT: 17799B
- [ ] "disabled" grey: bbb

**Comment by an-empty-string** [comment]
UI header: blue darken-3

**Comment by an-empty-string** [comment]
good enough for now(tm)
