### ISSUE TITLE
confirmation email for teams

### ISSUE THREAD

**Issue by laudiacay** [tjcsl/ctf-platform#5]
lets do a confirmation email for registry? (and have space for all the members' emails too, maybe? but that's less necessary)

**Comment by an-empty-string** [comment]
note to self: sendgrid

**Comment by an-empty-string** [comment]
in progress, blocking on sendgrid support

**Comment by an-empty-string** [comment]
resolved in 3ffbbce5512b5edc73442bc9d9e29551621cdcd8
