### ISSUE TITLE
integrate our logo into lots of places

### ISSUE THREAD

**Issue by laudiacay** [tjcsl/ctf-platform#6]
https://github.com/TJCSec/ctf-site-orig here is the design from the old site- the logo should be there somewhere, otherwise we can pull the old one. We might want a new favico or whatever, maybe a transparent background this year to go with the new design we have otherwise? Also we should change things to the trademark fonts from last year for brand continuity

**Comment by an-empty-string** [comment]
there's https://github.com/TJCSec/ctf-site-orig/blob/master/site/img/logo.svg but the color scheme might not work. thoughts?

**Comment by an-empty-string** [comment]
also, this should definitely be in the promo site/landing page but i'm not sure about the actual scoreboard

**Comment by an-empty-string** [comment]
closing until we have a proper landing page up
