### ISSUE TITLE
Solved problems....

### ISSUE THREAD

**Issue by laudiacay** [tjcsl/ctf-platform#7]
solved problems are all bunched together, but unsolved problems are not. We could probably put them back to being all bunched together (solved/unsolved/open/unopened/whatever) if we put some kind of 3D-ish effect or a subtle glow or a different color or a different size on the headers of problems. Before the headers didn't stick out, and separating the problems made them stick out. 

I'm not sure about just having everything separate, having all those little bitty "solved" bars being separate might clutter up the page. If they are all really uniform it might work out, but we can't put like those weird "first solve" non-uniform badges on them if we have a bunch of separate small closed bars on the page.

**Comment by an-empty-string** [comment]
let's go with different colors for headers. in progress...
