### ISSUE TITLE
new icons

### ISSUE THREAD

**Issue by laudiacay** [tjcsl/ctf-platform#8]
I'll find us some alternatives to the material design icons soon, they look a little too googley. At the least we need to make them us-colored and add some shadowing? worry about this later?

**Comment by an-empty-string** [comment]
font awesome maybe?

**Comment by laudiacay** [comment]
uhh ill look?

**Comment by an-empty-string** [comment]
also, checkbox styling can't be changed. the icons used to show solved problems can, though

**Comment by laudiacay** [comment]
could we change to the toggle switch thingy then? the black check looks nice, but can we change it to a navy blue if we want eventually?

**Comment by an-empty-string** [comment]
checkbox looks better for now, we can revisit this later maybe
